# Generated by Django 3.0.6 on 2020-06-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
