# Generated by Django 3.0.6 on 2020-06-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200605_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postUrl',
            field=models.TextField(default=1001),
            preserve_default=False,
        ),
    ]
