# Generated by Django 3.0.6 on 2020-06-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_posturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postUrl',
            field=models.TextField(blank=True),
        ),
    ]
