# Generated by Django 3.0.6 on 2020-06-03 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('batchName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('dateOfBirth', models.DateField(null=True)),
                ('phone', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('guardianPhone', models.CharField(max_length=200)),
                ('sectionName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendanceDate', models.DateField()),
                ('AttendanceResult', models.CharField(max_length=20)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
    ]
