# Generated by Django 3.0.7 on 2020-06-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Content',
            new_name='TellUs',
        ),
    ]
