# Generated by Django 3.0.6 on 2020-06-04 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseCode', models.CharField(max_length=100)),
                ('courseName', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('sectionName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Section')),
            ],
        ),
    ]
