# Generated by Django 3.0.6 on 2020-06-04 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='courseName',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='home.Course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='studentId',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
    ]
