# Generated by Django 3.0.6 on 2020-06-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_attendance_coursename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
