# Generated by Django 3.0.6 on 2020-06-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendanceDate', models.DateField()),
                ('attendanceDateResult', models.CharField(max_length=50)),
                ('courseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
    ]
