# Generated by Django 3.0.7 on 2020-06-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendanceDateResult',
        ),
    ]
