# Generated by Django 3.0.7 on 2020-06-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(default=False, max_length=60),
            preserve_default=False,
        ),
    ]
