# Generated by Django 3.0.7 on 2020-06-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200612_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
    ]
